### ISSUE TITLE
lost 1 million RDD

### ISSUE THREAD

**Issue by ChuckWeiner** [reddcoin-project/reddsight#14]
on 5/18/2020 I logged into my wallet, then apparently lost internet service, and sent 1 million RDD and they disappeared. Rb7xHiNFqJtKyRKEuaqPpvMzef83FxVxzC . They are not in my wallet or the wallet I sent them to.

**Comment by lionzeye** [comment]
You haven't lost the coins as they're still tied to that address. What most likely happened is that the transaction is in an unconfirmed state, but only in your local wallet. Restart the wallet with the - zapwallettxes -rescan parameters which should restore your balance as it removes the transaction that's stuck. Back up your wallet.dat beforehand.

**Comment by lionzeye** [comment]
Closing this issue as it appears the funds were successfully sent.
